from typing import Protocol, Optional
from bot.models.user import User


class UserRepository(Protocol):
    async def init(self) -> None: ...

    async def get_by_tg_id(self, tg_id: int) -> Optional[User]: ...

    async def create(self, user: User) -> User: ...

    async def update(self, user: User) -> User: ...

    async def get_all_users(self) -> list[User]: ...
